### ISSUE TITLE
Incorrect display when TickPlacement = BottomRight

### ISSUE THREAD

**Issue by remarkked** [tdcosta100/SliderWithTickLabels#2]
TickPlacement = Both:
![image](https://github.com/tdcosta100/SliderWithTickLabels/assets/80647291/9fba8f73-67fb-4274-aacf-4a8c29d59393)

TickPlacement = TopLeft:
![image](https://github.com/tdcosta100/SliderWithTickLabels/assets/80647291/e252250d-8c20-4316-9033-7332ccbdb6c5)

TickPlacement = BottomRight:
![image](https://github.com/tdcosta100/SliderWithTickLabels/assets/80647291/6b6062a0-1230-48a7-9373-745e73cae9a6)

**Comment by tdcosta100** [comment]
Thank you for reporting this problem! I just commited a change that fixes it. Please tell me if it works now.

**Comment by remarkked** [comment]
@tdcosta100 everything works fine now!
Everything works as expected, but I'm still getting strange binding errors no matter slider properties (including Orientation) are set or not.
Binding error:
Context = null
Binding path = Orientation
Source = ContentPresenter
Target = ContentPresenter
Description: 
Can't find source: RelativeSource FindAncestor, AncestorType='SliderWithTickLabels.SliderWithTickLabels', AncestorLevel='1'.

**Comment by tdcosta100** [comment]
I have these errors too, since the first implementation. I will investigate, hope I can find where is the error.

**Comment by tdcosta100** [comment]
I investigated and you can safely ignore these errors, for now. As far as I could check, they are caused by intermediate steps in the rendering process.
